### PR TITLE
Add consul health endpoint

### LINKED ISSUE #24: consul health endpoint required by promtheus v2.17.0
The following commit to prometheus
https://github.com/prometheus/prometheus/commit/9b9c58aea8e0043bb944961fb776b48ac602c7f9
looks like prometheus is now querying service health endpoint (/v1/health/service/...) which isn't implemented by eureka-consul-adapter.

V2.16.0 seems to be the last prometheus release that is working as of now.

### PR DESCRIPTION
**Pull request by avaneev95**
This PR contains an implementation of the consul health endpoint `/v1/health/service` for Prometheus v2.17.0. Closes #24

### CODE REVIEW

**Comment by tine2k** [comment]
Thank you very much for your contribution, @avaneev95. I'll look into this within the next days.

**Comment by rmie** [comment]
I tested it briefly, and it seems like eureka metadata labels are now published differently:
```
__meta_consul_metadata_* => __meta_consul_service_metadata_*
```

**Comment by avaneev95** [comment]
@rmie It's correct behaviour for v1.3.0 when `eurekaConsulAdapter.useNodeMeta` is not set or set to `false`. See #16

**Comment by rmie** [comment]
@avaneev95 thanks for clarification, indeed that's what I was missing

**Comment by tine2k** [comment]
Just released this as 1.4.0 on Central. Thank you both for your help.

**Pull request merged**
